<center><img src="https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true" width="240" height="100" /></center>

**<center><h3>Data Operations with Numpy Assignment Solution</h3></center>**

In [1]:
import numpy as np

---
**<h4>Question 1:** Create a function that generate a null vector of size N containing a certain value at specified position.</h4>

- For example, you passed `vector_size = 5`, `val = 2`, and `pos = 2`.

- The value returned will be `[0. 0. 2. 0. 0.]`.

<details>

**<summary>Hint:</summary>**

- Initialize vector with the zeros of specified vector size. You can use the numpy's function here.

- Pass the index value of specified position and assign it the passed value. 

- Display the result.

</details>

In [2]:
def createNull(vector_size=None, val=None, pos=None):
  """Creates a null vector with a certain value at certain positions."""

  # Initialize vector with the passed vector_shape
  vector = np.zeros(shape=vector_size)

  # Assign the passed value to the vector at specified position
  vector[pos] = val

  # Display the result
  print('Output Vector:', vector)

In [3]:
createNull(vector_size=5, val=2, pos=2)

Output Vector: [0. 0. 2. 0. 0.]


---
**<h4>Question 2:** Create a function that generate a vector of size N with values ranging from A to B.</h4>

- For example, you passed `vector_size = 11`, `start_val = 0`, and `end_val = 2`.

- The value returned will be `[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]`.

<details>

**<summary>Hint:</summary>**

- You can achieve this question by using the numpy's linspace functionality.

</details>

In [4]:
def vectorBetween(vector_size=None, start_val=None, end_val=None):
  """Creates a null vector of size N containing values between certain values."""

  # Initialize vector with the passed vector_shape
  vector = np.linspace(start=start_val, stop=end_val, num=vector_size)

  # Display the result
  print('Output Vector:', vector)

In [5]:
vectorBetween(vector_size=11, start_val=0, end_val=2)

Output Vector: [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


---
**<h4>Question 3:** Create a function that performs the normalization over the matrix as shown below in the example.</h4>

- Create a 2-dimensional matrix of size N X M.
  - Let's say you created a matrix of 3 X 3.
    - `|0 1 2|`
    - `|3 4 5|`
    - `|6 7 8|`

- Subtract the matrix with the mean of the rows of the matrix.
  - The mean of the rows of the matrix came out to be `1, 4, 7`.
    - `|0 1 2| - |1|`
    - `|3 4 5| - |4|`
    - `|6 7 8| - |7|`

- Divide the whole matrix by the twice size of the max value present in the matrix.
  - The max value of the matrix elements came out to be 1.
    - `|-1 0 1| ÷ (2*1)`
    - `|-1 0 1| ÷ (2*1)`
    - `|-1 0 1| ÷ (2*1)`

- Display the final result.
    - `|-0.5  0   0.5|`
    - `|-0.5  0   0.5|`
    - `|-0.5  0   0.5|`

<details>

**<summary>Hint:</summary>**

- Pass an array of elements along with the matrix dimensions of nrows and ncols.

- Reshape the array with the specified matrix dimensions. You can use numpy's reshape functionality.

- Get the mean of the matrix in a row-wise fashion. You may need to reshape the mean matrix in a column-wise structure.

- Subtract the elements of the matrix with the mean matrix.

- Extract the maximum value present in the matrix and multiply it with the number 2.

- Divide the subtracted matrix with the extracted maximum value and display the result.

</details>

In [16]:
def matrixNormalization(input_matrix=None, nrows=None, ncols=None):
  """Perform normalization over the input matrix of N X M."""

  # Reshape the input matrix according to the passed dimension
  matrix = np.reshape(input_matrix, nrows, ncols)

  # Subtract the matrix with the mean of the matrix (row-wise fashion)
  # Matrix mean will require reshaping to the column-wise structure
  matrix = matrix - matrix.mean(axis=1)[:, None]

  # Extract the max value present in the matrix after subtraction
  max_val = matrix.max()

  # Divide the matrix by the twice size of the max value present in the matrix
  matrix_norm = matrix / (2*max_val)

  # Display the result
  print(matrix_norm)

In [17]:
matrixNormalization(np.arange(0, 9),3,3)

TypeError: order must be str, not int

---
**<h4>Question 4:** Create a function that generates a matrix of shape N X M with random values in a decreasing order.</h4>

- For example, you passed 9 random values such as:
  -  `[0.83086063, 0.00536904, 0.58981977, 0.76704028, 0.55501003, 0.91354796, 0.57879962, 0.76508311, 0.66402454]`.

- The value returned will be:
    - `|0.83086063 0.00536904 0.58981977|`
    - `|0.76704028 0.55501003 0.91354796|`
    - `|0.57879962 0.76508311 0.66402454|`

<details>

**<summary>Hint:</summary>**

- Initialize a vector with random values of specified size in the function.

- Sort the vector in descending order using sorted() method. You may require to convert the sorted value to an array again.

- Reshape the sorted vector using the reshape functionality present in the numpy package.

- Display the final output.

</details>

In [10]:
def randMatrix(vectorsize=None, nrows=None, ncols=None):
  """Creates a random matrix of shape N X M with random values in decreasing order."""

  # Initialize a variable with random values with the specified randval
  vector = np.random.random(size=vectorsize)

  # Sort the vector in a descending order
  vector_sort = np.array(sorted(vector, reverse=True))

  # Reshape the sorted vector with the specified shape
  vector_sort = np.reshape(vector_sort, newshape=(nrows, ncols))

  # Dispaly the output
  print(vector_sort)

In [11]:
randMatrix(vectorsize=9, nrows=3, ncols=3)

[[0.94765305 0.90650651 0.80042557]
 [0.62695791 0.28623851 0.28227783]
 [0.23918856 0.113533   0.09326914]]


C:\Users\tejas\AppData\Local\Temp\ipykernel_6780\3233664078.py:11: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  vector_sort = np.reshape(vector_sort, newshape=(nrows, ncols))


---
**<h4>Question 5:** Create a function that generates an array ranging from A to B and perform inverse-sign on inclusive values.</h4>

- For example, you passed `[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]`.

- The final output will be `[-5,  4,  3,  2,  1,  0, -1, -2, -3,  4]`.

<details>

**<summary>Hint:</summary>**

- Initialize an array of specified size using start and stop position.

- If array>start and array<stop-1, then array = array * -1.

- You can also use conditional operation, mathematical operation and assigning operation in combination.

- If not sure, refer to the solution sheet.

</details>

In [18]:
def inclusiveInverse(arrstart=None, arrstop=None):
  """Returns an array ranging from A to B and perform inverse sign on inclusive values."""

  # Generates an array of specified length
  arr = np.arange(arrstart, arrstop)

  # Perform inverse operation on inclusive values
  arr[(arr>arrstart) & (arr<(arrstop-1))] *= -1

  return arr

In [19]:
inclusiveInverse(arrstart=-5, arrstop=5)

array([-5,  4,  3,  2,  1,  0, -1, -2, -3,  4])

---
**<h4>Question 6:** Creates a function that returns a N size array on replacing max & min values with a specified value in reverse order.</h4>

- For example, you passed `arrlow = 1`, `arrhigh = 10`, `arrsize = 10`, `replacemaxby = 2`, and `replaceminby = 4`.

- The array generated with the specified values is `[5 8 8 3 3 1 7 4 4 5]`.

- After replacing the max and min value the array becomes `[5 2 8 3 3 4 7 4 4 5]`.

- On sorting the array in reverse direction (decreasing order) it becomes `[8 7 5 5 4 4 4 3 3 2]`. 

<details>

**<summary>Hint:</summary>**

- Initiate a random array of specified size along with the low and high values.

- For this you can use numpy's random integer functionality.

- Replacing max and min value in an array with a specified value.

- For the above step you can use numpy's argmax functionality.

- Reverse the modified array after replacing values using sorted() function of python.

</details>

In [20]:
def randReplaceReverse(arrlow=None, arrhigh=None, arrsize=None, replacemaxby=None, replaceminby=None):
  """Returns a reverse sorted array after replacing max & min values with a specified value."""

  # Initiate a random array of specified size along with the low and high values
  randvector = np.random.randint(low=arrlow, high=arrhigh, size=arrsize)

  # Display the original array
  print('Original array:', randvector)

  # Replacing max value in an array with a specified value
  randvector[randvector.argmax()] = replacemaxby

  # Replacing min value in an array with a specified value
  randvector[randvector.argmin()] = replaceminby

  # Display the modified array
  print('Modified array:', randvector)

  # Reverse the modified array
  randvector = np.array(object=sorted(randvector, reverse=True))

  # Display the reversed array
  print('Reversed array:', randvector)

In [21]:
randReplaceReverse(arrlow=1, arrhigh=10, arrsize=10, replacemaxby=2, replaceminby=4)

Original array: [7 5 2 2 3 5 7 6 8 9]
Modified array: [7 5 4 2 3 5 7 6 8 2]
Reversed array: [8 7 7 6 5 5 4 3 2 2]


---
**<h4>Question 7:** Create a function that returns the euclidean distance between two arrays.</h4>

- For example, you passed two arrays such as : `[1, 2, 3, 4, 5]` and `[4, 5, 6, 7, 8]`

- The returned output will be `6.708`.

<details>

**<summary>Hint:</summary>**

- The formula that is used to calculate euclidean distance is $\sqrt {\sum _{i=1}^{n}  \left( q_{i}-p_{i}\right)^2 } $ where p and q are two points in Euclidean n-space.

- There are many ways to achieve this question. You can use numpy's linalg class file to directly compute the distance.

- Typecast the input to numpy array as it is the requirement for norm() functionality of linalg class file.

- Return the final output.

</details>

In [22]:
def calculateEuclidean(arr1=None, arr2=None):
  """Estimates euclidean distances between two arrays."""

  # Typecast to array, if not
  arr1 = np.array(arr1)
  arr2 = np.array(arr2)

  # Return the euclidean distance
  return np.linalg.norm(x=arr1-arr2)

---
**<h4>Question 8:** Create a function that generates an $N_1$ X $N_2$ matrix filled with a chessboard pattern.</h4>

- For example, you passed `N1 = 8`, and `N2 = 8`.

- The output will be as shown below:

<center>|0 1 0 1 0 1 0 1|</center>
<center>|1 0 1 0 1 0 1 0|</center>
<center>|0 1 0 1 0 1 0 1|</center>
<center>|1 0 1 0 1 0 1 0|</center>
<center>|0 1 0 1 0 1 0 1|</center>
<center>|1 0 1 0 1 0 1 0|</center>
<center>|0 1 0 1 0 1 0 1|</center>
<center>|1 0 1 0 1 0 1 0|</center>

<details>

**<summary>Hint:</summary>**

- Initialize a matrix with the specified dimensions.

- You can use the numpy's zeros() functionality to do this task.

- Then for even rows and odd columns using indexing and striding place value = 1.

- For odd rows and even columns using indexing and striding place value = 1.

- Display the result.

</details>

In [23]:
def createChessMatrix(N1=None, N2=None):
  """Generates a matrix of dimension N1 X N2."""

  # Initialize a matrix with zero of specified dimensions
  matrix = np.zeros((N1, N2), dtype=int)

  # For even rows and odd columns
  matrix[1::2,::2] = 1

  # For odd rows and even columns
  matrix[::2,1::2] = 1

  # Display the output
  print(matrix)

In [24]:
createChessMatrix(N1=10, N2=10)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


---
**<h4>Question 9:** Create a function that displays the number of weekdays and dates ranging from Date A to Date B.</h4>

- For example, you passed `start_date = 1994-04` and `end_date = 1994-05`.

- The returned output will be: `Total Weekdays: 21`

- `[1994-04-01, 1994-04-02, 1994-04-03, 1994-04-04, 1994-04-05, 1994-04-06, 1994-04-07, 1994-04-08, 1994-04-09, 1994-04-10, 1994-04-11, 1994-04-12, 1994-04-13, 1994-04-14, 1994-04-15, 1994-04-16, 1994-04-17, 1994-04-18, 1994-04-19, 1994-04-20, 1994-04-21, 1994-04-22, 1994-04-23, 1994-04-24, 1994-04-25, 1994-04-26, 1994-04-27, 1994-04-28, 1994-04-29, ,1994-04-30]`

<details>

**<summary>Hint:</summary>**

- You can use numpy's busday_count() functionality to estimate total weekday frequency.

- Next, you need to generate dates ranging from Date A to Date B.

- This can be achieved using the help of numpy's arange() functionality.

- **Note:** Make sure the dtype is set to datetime64[D].

- Display out the final result.

</details>

In [25]:
def generateDates(start_date=None, end_date=None):
  """Estimates number of weekdays and dates ranging from Date A to Date B."""

  # Estimate weekday frequency ranging from Date A to Date B
  weekdays_freq = np.busday_count(begindates=start_date, enddates=end_date)

  # Create dates ranging from Date A to Date B
  dates = np.arange(start_date, end_date, dtype='datetime64[D]')

  # Display the weekdays frequency
  print('Total Weekdays:', weekdays_freq)

  # Display the dates ranging from Date A to Date B
  print('Dates: ', dates)

In [26]:
generateDates(start_date='1994-04', end_date='1994-05')

Total Weekdays: 21
Dates:  ['1994-04-01' '1994-04-02' '1994-04-03' '1994-04-04' '1994-04-05'
 '1994-04-06' '1994-04-07' '1994-04-08' '1994-04-09' '1994-04-10'
 '1994-04-11' '1994-04-12' '1994-04-13' '1994-04-14' '1994-04-15'
 '1994-04-16' '1994-04-17' '1994-04-18' '1994-04-19' '1994-04-20'
 '1994-04-21' '1994-04-22' '1994-04-23' '1994-04-24' '1994-04-25'
 '1994-04-26' '1994-04-27' '1994-04-28' '1994-04-29' '1994-04-30']


---
**<h4>Question 10:** Create a function that performs padding of size S with value P over the numpy array.</h4>

- For example, you passed `arr = None`, `noarrshape = (3, 3)`, `pad_size = 2`, `pad_val = 7`.

- The returned output will be:

<center>|7 7 7 7 7 7 7|</center>
<center>|7 7 7 7 7 7 7|</center>
<center>|7 7 1 1 1 7 7|</center>
<center>|7 7 1 1 1 7 7|</center>
<center>|7 7 1 1 1 7 7|</center>
<center>|7 7 7 7 7 7 7|</center>
<center>|7 7 7 7 7 7 7|</center>


<details>

**<summary>Hint:</summary>**

- Check if the passed array exists or not.

- If the array is none, then generate a default array with ones of specified shape.

- Return the padded array of size S with the padded value P.

- To achieve this, you can use numpy's pad() functionality.

- Next, if the array is passed, then perform padding using pad() and return it.

</details>

In [27]:
def padArray(arr=None, noarrshape=None, pad_size=None, pad_val=None):
  """Performs padding of size S over an array."""

  # Check if the passed array is empty or not
  if arr == None:
    
    # Generate array with ones of specified size
    arr = np.ones(shape=noarrshape)

    # Return the padded array
    return np.pad(array=arr, pad_width=pad_size, constant_values=pad_val)

  # Return the padded array if array is passed
  return np.pad(array=arr, pad_width=pad_size, constant_values=pad_val)

In [28]:
padArray(arr=None, noarrshape=(3, 3), pad_size=2, pad_val=7)

array([[7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 1., 1., 1., 7., 7.],
       [7., 7., 1., 1., 1., 7., 7.],
       [7., 7., 1., 1., 1., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.]])